#!/usr/bin/env dotnet
#:property AllowUnsafeBlocks=true
#:property PublishAot=false
#:property SignAssembly=false
// 生成 src/VelaShell/Services/XServer/BundledKeymaps.cs:内置 X 服务端在设置里手选布局时用的键位表。
//
// 数据来自 xkeyboard-config(经 libxkbcommon 按 RMLVO 名编译,规则 evdev、型号 pc105),只在 Linux 上跑:
//   dotnet publish scripts/xserver/keymaps/generate.cs -r linux-x64 --self-contained -o out
//   (在装了 libxkbcommon0 与 xkb-data 的 Linux 上)./out/generate us gb de fr … > BundledKeymaps.cs
// 每个布局导出 X 键码 10–61 与 94 各键的第 1–4 级键值(布局组 1);右 Alt 不是 Level3 键时第 3、4 级记 0。
using System.Runtime.InteropServices;
using System.Text;

byte[] keycodes = [.. Enumerable.Range(10, 52).Select(k => (byte)k), 94];
string version = File.Exists("/var/lib/dpkg/status") ? DebianVersion("xkb-data") : "unknown";

StringBuilder o = new();
o.AppendLine("// <auto-generated>");
o.AppendLine("// 由 scripts/xserver/keymaps/generate.cs 生成,不要手改。");
o.AppendLine($"// 数据来源:xkeyboard-config(Debian xkb-data {version}),经 libxkbcommon 按 rules=evdev、model=pc105 编译;");
o.AppendLine("// xkeyboard-config 按 MIT / X11 风格的许可发布。");
o.AppendLine("// </auto-generated>");
o.AppendLine();
o.AppendLine("namespace VelaShell.Services.XServer;");
o.AppendLine();
o.AppendLine("/// <summary>");
o.AppendLine("/// 随程序带的键位表:XKB 布局名 → X 键码 10–61 与 94 各键第 1–4 级的键值(每键 4 个,依次排列;0 = 没有)。");
o.AppendLine("/// 设置里手选布局时,内置 X 服务端用它(见 <see cref=\"HostKeymap.FromBundled\" />)。");
o.AppendLine("/// </summary>");
o.AppendLine("internal static class BundledKeymaps");
o.AppendLine("{");
o.AppendLine("    public static readonly IReadOnlyDictionary<string, uint[]> Layouts = new Dictionary<string, uint[]>(StringComparer.Ordinal)");
o.AppendLine("    {");
foreach (string layout in args)
{
    uint[] levels = Compile(layout) ?? throw new InvalidOperationException($"布局 {layout} 编译失败");
    o.AppendLine($"        [\"{layout}\"] =");
    o.AppendLine("        [");
    for (int i = 0; i < keycodes.Length; i++)
    {
        o.AppendLine($"            {string.Join(", ", levels.Skip(i * 4).Take(4).Select(s => $"0x{s:x}"))},   // {keycodes[i]}");
    }
    o.AppendLine("        ],");
}
o.AppendLine("    };");
o.AppendLine("}");
Console.Write(o.ToString().Replace("\r\n", "\n"));

unsafe uint[]? Compile(string layout)
{
    nint context = Xkb.xkb_context_new(0);
    nint rules = Marshal.StringToCoTaskMemUTF8("evdev"), model = Marshal.StringToCoTaskMemUTF8("pc105"),
        name = Marshal.StringToCoTaskMemUTF8(layout), empty = Marshal.StringToCoTaskMemUTF8("");
    try
    {
        nint* names = stackalloc nint[5] { rules, model, name, empty, empty };
        nint keymap = Xkb.xkb_keymap_new_from_names(context, names, 0);
        if (keymap == 0)
        {
            return null;
        }
        try
        {
            // 右 Alt(键码 108)是 Level3 键时才保留第 3、4 级:内置服务端只把右 Alt 当 AltGr。
            bool level3 = Level(keymap, 108, 0) is 0xfe03 or 0xfe04 or 0xfe05;   // ISO_Level3_Shift / Latch / Lock
            List<uint> result = [];
            foreach (byte k in keycodes)
            {
                for (uint level = 0; level < 4; level++)
                {
                    result.Add(level >= 2 && !level3 ? 0 : Level(keymap, k, level));
                }
            }
            return [.. result];
        }
        finally
        {
            Xkb.xkb_keymap_unref(keymap);
        }
    }
    finally
    {
        Marshal.FreeCoTaskMem(rules);
        Marshal.FreeCoTaskMem(model);
        Marshal.FreeCoTaskMem(name);
        Marshal.FreeCoTaskMem(empty);
        Xkb.xkb_context_unref(context);
    }
}

unsafe uint Level(nint keymap, uint keycode, uint level)
{
    uint* syms = null;
    return Xkb.xkb_keymap_key_get_syms_by_level(keymap, keycode, 0, level, &syms) > 0 && syms != null ? syms[0] : 0;
}

string DebianVersion(string package)
{
    foreach (string line in File.ReadLines("/var/lib/dpkg/status").SkipWhile(l => l != $"Package: {package}"))
    {
        if (line.StartsWith("Version: ", StringComparison.Ordinal))
        {
            return line[9..];
        }
    }
    return "unknown";
}

static unsafe partial class Xkb
{
    private const string Lib = "libxkbcommon.so.0";

    [LibraryImport(Lib)]
    public static partial nint xkb_context_new(int flags);

    [LibraryImport(Lib)]
    public static partial void xkb_context_unref(nint context);

    [LibraryImport(Lib)]
    public static partial nint xkb_keymap_new_from_names(nint context, nint* names, int flags);

    [LibraryImport(Lib)]
    public static partial void xkb_keymap_unref(nint keymap);

    [LibraryImport(Lib)]
    public static partial int xkb_keymap_key_get_syms_by_level(nint keymap, uint key, uint layout, uint level, uint** symsOut);
}
